### ISSUE TITLE
[Errors]Uncaught (in promise) undefined

### ISSUE THREAD

**Issue by yagamilighttuski** [ClearlyKyle/Language_Reactor_to_Anki#2]
The chrome version i'm using: 118.0.5993.120 
Language Reactor Version: 5.0.0
Language_Reactor_to_Anki Version: 1.0
Then i encountered this problem, how should i fix it?
![image](https://github.com/ClearlyKyle/Language_Reactor_to_Anki/assets/78994336/afd93a9d-a314-468f-811e-c0f7f3011d28)

**Comment by yagamilighttuski** [comment]
The image seems unclear. This is the content in image:

**Uncought(in promise) undefined**
### Context
>src/popup/popup.html

### Stack Trace
>src/popup/popup.js:189(anonymous function)

**Comment by ClearlyKyle** [comment]
Should be fixed with latest commit. Make sure Anki is open first before using the extension

**Comment by yagamilighttuski** [comment]
> Should be fixed with latest commit. Make sure Anki is open first before using the extension
![Snipaste_2023-11-05_12-47-51](https://github.com/ClearlyKyle/Language_Reactor_to_Anki/assets/78994336/8d622422-7fbb-45c5-929e-9a51f5da416b)


Seems like i still can't see `Anki` button

**Comment by yagamilighttuski** [comment]
My Anki is open and has `AnkiConnect` 
![Snipaste_2023-11-05_12-55-04](https://github.com/ClearlyKyle/Language_Reactor_to_Anki/assets/78994336/f7b30f4c-7e91-46f3-8b82-7774598cf1e4)

**Comment by yagamilighttuski** [comment]
And my settings are like this
![Snipaste_2023-11-05_13-02-35](https://github.com/ClearlyKyle/Language_Reactor_to_Anki/assets/78994336/52e8c410-095e-41ce-bac8-1f10c472e545)

**Comment by ClearlyKyle** [comment]
To get the Anki option in with the YouTube videos, you need to use the other extension:
https://github.com/ClearlyKyle/Language-Learning-With-Anki

They are currently separate extensions, one for www.languagereactor.com and the other for YouTube videos. But now you have said this, I think in the future I will combine these extensions into one

**Comment by yagamilighttuski** [comment]
> To get the Anki option in with the YouTube videos, you need to use the other extension: https://github.com/ClearlyKyle/Language-Learning-With-Anki
> 
> They are currently separate extensions, one for [www.languagereactor.com](http://www.languagereactor.com) and the other for YouTube videos. But now you have said this, I think in the future I will combine these extensions into one

Oh i see. thank you very much for all the work you've done. I tried to use `Language-Learning-With-Anki` you mentioned just now, but i got an error like this ![Snipaste_2023-11-05_18-29-55](https://github.com/ClearlyKyle/Language_Reactor_to_Anki/assets/78994336/0ec9ee68-4fa2-4d4f-abb5-b38c013d6c94)

**Comment by ClearlyKyle** [comment]
I added a commit to fix this now

**Comment by yagamilighttuski** [comment]
No errors now, but i still can't see `Anki` button 
![Snipaste_2023-11-05_19-29-03](https://github.com/ClearlyKyle/Language_Reactor_to_Anki/assets/78994336/db05103e-c7e4-4fc6-aa61-1360f946d89e)

**Comment by ClearlyKyle** [comment]
Sorry but I cannot seem to recreate this issue. Normally a refresh or reopen the same video in a new tab should fix it

**Comment by yagamilighttuski** [comment]
Sorry for bothering, I can see `Anki` button now, but when i click `Anki` button it seems not adding card to my Anki deck. When i check my extension, i found an error.
![Snipaste_2023-11-06_11-12-51](https://github.com/ClearlyKyle/Language_Reactor_to_Anki/assets/78994336/03037e02-0344-46c3-9366-9797642785cd)
![Snipaste_2023-11-06_11-13-22](https://github.com/ClearlyKyle/Language_Reactor_to_Anki/assets/78994336/86e702ca-dbf0-4275-bab5-e37aaaac0d49)

**Comment by ClearlyKyle** [comment]
This should be fixed in last commit, but I will have a look again

**Comment by yagamilighttuski** [comment]
Thanks for your patience. I refreshed several times but I still can't add card to my deck

**Comment by ClearlyKyle** [comment]
Do you have any errors showing for this?

**Comment by yagamilighttuski** [comment]
You mean whether there will be a pop-up window displays error when i click `Anki` button? Then no, the problem i am facing is more like no response, i click `Anki` button, nothing happend, then i go check my Anki deck, find no card added, it's still zero card within the deck. Is this extension work normally in your computer?

**Comment by ClearlyKyle** [comment]
When the Anki button is clicked, a pop-up in the top right should appear and say "Success" or "Error", if you are not seeing this then the error must come before sending data to Anki. 

Does it work if you click a word on the subtitle then click the Anki button? Clicking words on the sidebar then the Anki button can be inconsistent for now.

**Comment by yagamilighttuski** [comment]
Oh yeah it's working now, click subtitle works normally, so maybe it's because i used to click sidebar. Thanks for your work, it's a great help for language learner who enjoy watching interviews!

**Comment by ClearlyKyle** [comment]
Thank you for raising these issues, I am glad you are getting it to work now.
